### ISSUE TITLE
Plugin broken with Version 43 (38999)

### ISSUE THREAD

**Issue by SofieHaugeKatan** [nilshoenson/shared-text-styles#11]
First thank you for an amazing plugin, literally the first thing I do when creating a new document is to import the correct text styles. 

That is also why i'm devastated that it stoped working today after updating to sketch v43. It simply does not import the styles when choosing the json file. 

Is it something you can fix🤞
Thank you so much

**Comment by louriach** [comment]
Also finding this issue. The export screen seems to work fine, but there is no file generated.

**Comment by nilshoenson** [comment]
Thanks for reporting this! Looks like Sketch changed the API a bit with v43. I'll take a look at it.

**Comment by MaximusMcCann** [comment]
Presuming same reason.  I click export and the `save`, but no file is generated :/
