### ISSUE TITLE
Import-export doesn't work with certain people

### ISSUE THREAD

**Issue by raulendymion** [nilshoenson/shared-text-styles#14]
I've been testing the plugin, and it works perfectly on my computer and different files and with some other people. However, it doesn't work with one of my colleagues. He has the same sketch version that I have, no other plugins and he has tried to reinstall both sketch and your plugin with no success. 

He's able to import his own files (test-text-styles-1.json) but when I take his file, do a modification (test-text-styles-2.json), and he tries to import it then it doesn't work. 

[json.zip](https://github.com/nilshoenson/shared-text-styles/files/1035463/json.zip)

**Comment by dergraph** [comment]
same here, as well as on collegues machine, same version latest everything

**Comment by nilshoenson** [comment]
This is weird, I'll see what I can do.

**Comment by raulendymion** [comment]
we can give you more info or logs if you tell us what to do.
