### ISSUE TITLE
Does not export grouped styles organized with "/"

### ISSUE THREAD

**Issue by yenloftin** [nilshoenson/shared-text-styles#17]
I got really excited about this plugin and was able to successfully export and import styles initially.  But, I like to keep my styles organized by grouping them with "/." (Ex. Headers/H1/Desktop.) But once I group styles, I am unable to export.

I've tested it and was able to export another file that had styles which weren't grouped.

**Comment by yenloftin** [comment]
I'm on Sketch 45.1

**Comment by nilshoenson** [comment]
I'll take a look at it, thanks for letting me know!
