### ISSUE TITLE
Does Not Import Emoji characters

### ISSUE THREAD

**Issue by chevtron** [nilshoenson/shared-text-styles#18]
![exported](https://user-images.githubusercontent.com/7834490/28034667-b3a7dc40-6566-11e7-8836-299191b03e8b.png)
![imported](https://user-images.githubusercontent.com/7834490/28034668-b3ae517e-6566-11e7-93df-017994e62f1d.png)

**Comment by agabewill** [comment]
+1 to this. I'm using left and right arrows to indicate alignment, which also don't get imported correctly. I was able to fix it by escaping the special characters in the JSON file, but it'd be nice for this to be automated.

<img width="100%" alt="screen shot 2017-10-25 at 11 21 20 am" src="https://user-images.githubusercontent.com/1717867/32007154-b9580232-b976-11e7-8639-46fc6ef2e006.png">
