### ISSUE TITLE
Alignment and spacing settings

### ISSUE THREAD

**Issue by russgoodman** [nilshoenson/shared-text-styles#2]
Is it possible to also pull in the alignment and spacing details as well? The current set of data isn't quite enough for this to be useful for us. The styles default to left aligned and the line height being the same as the text size.

**Comment by nilshoenson** [comment]
Hi Russ! Thanks for the suggestion. Alignment and spacing details will be added shortly.

**Comment by nilshoenson** [comment]
Fixed now! [See the commit](https://github.com/nilshoenson/shared-text-styles/commit/5da5cd9d4e85dc894d12e578540dc910b2b7d345)
