### ISSUE TITLE
Doesn't work with v47

### ISSUE THREAD

**Issue by lajlev** [nilshoenson/shared-text-styles#20]

**Comment by olafchou** [comment]
![jietu20171012-141940](https://user-images.githubusercontent.com/19890798/31482013-dc0384ea-aeeb-11e7-87eb-a1c5e932bcba.jpg)

couldn't import ,could you renew the plugin

**Comment by dpaolabr** [comment]
the problem is not the sketch 47, but the macOS High Sierra. My co-worker has the 47 but still on macOS Sierra 10.12 and it is working

**Comment by dpaolabr** [comment]
and it's only to import. export works fine

**Comment by olafchou** [comment]
<img width="281" alt="2017-10-18 08 21 15" src="https://user-images.githubusercontent.com/19890798/31695856-997a61da-b372-11e7-9ca7-5255f2abc97b.png">

**Comment by dpaolabr** [comment]
@olafchou same as me and I can't import.

**Comment by nilshoenson** [comment]
Thanks for letting me know all, I'll be working on a fix.

**Comment by nilshoenson** [comment]
Thanks for the pateience all! I just pushed an update which should fix the import issues. For now I'm closing this issue.

https://github.com/nilshoenson/shared-text-styles/releases/tag/1.4
