### ISSUE TITLE
`text-decoration: underline` missing in export

### ISSUE THREAD

**Issue by jenniesyip** [nilshoenson/shared-text-styles#25]
Steps to reproduce: 
- Created all of my text styles, the links are underlined. 
![image](https://user-images.githubusercontent.com/1864971/33651710-ace662ee-da1b-11e7-98cd-090154beb73d.png)

- Used plugin to export the styles to `text-styles.json` file
- Opened a new Sketch file, imported `text-styles.json` file and this is what is imported:
![image](https://user-images.githubusercontent.com/1864971/33651933-57f84da0-da1c-11e7-8306-4a9c9405d6e3.png)

**Comment by nilshoenson** [comment]
Hey Jenny, this should not be the case. I'll be working on a fix soon!

**Comment by jenniesyip** [comment]
@nilshoenson Thanks! 🙌

**Comment by nilshoenson** [comment]
This is now fixed! You can grab the update.

**Comment by jenniesyip** [comment]
Thank you!! ⚡️
