### ISSUE TITLE
Colors not exporting in v48

### ISSUE THREAD

**Issue by argomod** [nilshoenson/shared-text-styles#26]
Colors don't seem to be exporting along with the rest of the text styles. I believe this may be a bug with Sketch v48 since it made several tweaks to color functionality.

As a test, I created a bright red text style:
<img width="435" alt="screen shot 2017-12-06 at 3 47 16 pm" src="https://user-images.githubusercontent.com/34323218/33691458-29b99a26-da9d-11e7-9e5c-6aa00d56955e.png">

After exporting and importing, this is the result:
<img width="507" alt="screen shot 2017-12-06 at 3 48 09 pm" src="https://user-images.githubusercontent.com/34323218/33691465-2fba6af4-da9d-11e7-8a3d-a5af80952289.png">

Looking at the JSON, the color value is missing:
`{"styles":[{"name":"Test","font":"DINPro-Medium","size":44,"color":{},"alignment":0,"spacing":0,"lineHeight":0,"textTransform":0}]}`

Thanks for the help!

**Comment by jaredfancy** [comment]
I'm also experiencing this issue. Haven't found a solve.

**Comment by nilshoenson** [comment]
This looks to be because of the newly supported color profiles. Will be working on a fix!

**Comment by jjezowski** [comment]
Thanks for the update @nilshoenson. Just curious if you are close to a fix? Would be super helpful!

**Comment by clarewarburton** [comment]
Yes I love this plugin — and just updated to 48 and noticed this bug. Thanks for fixing!!

**Comment by nilshoenson** [comment]
I just pushed an update which should fix this! Thanks for the feedback all!
