### ISSUE TITLE
Sketch crashing

### ISSUE THREAD

**Issue by mcklowry** [nilshoenson/shared-text-styles#27]
Sketch crashes every time I try to import text styles. I have Sketch 48.1 and 1.4 of this plugin.

**Comment by slightlygilded** [comment]
having a similar issue. first time i tried importing, sketch crashed. second time and times after, it allowed the import but crashed when i tried to apply one of the imported styles. Using Sketch 48.1 and 1.4 of this plugin. i use this plugin very frequently, any help would be greatly appreciated. thanks!

**Comment by richardbruskowski** [comment]
Same here.

**Comment by szabinho** [comment]
Having the same issue with re-importing. Steps to re-create:

1. Create text styles in a "master" document
2. Export the styles
3. Open a new Sketch document and import the texts styles
4. Use the styles in this new document.
5. Change text styles in "master" document
6. Export styles from "master" document
7. Re-import to the other document 
8. Witness the crash

**Comment by nilshoenson** [comment]
I just pushed an update which should fix this. Thanks all!
