### ISSUE TITLE
Sketch crashing

### ISSUE THREAD

**Issue by marianneho** [nilshoenson/shared-text-styles#30]
Importing a text styles file crashes my Sketch. 
Trying to import into a Sketch a file with prior elements, and 2 other separate text styles. 

Sketch 48.1 
Mac OS 10.11.6
plugin version 1.5.2
  

Incident Identifier: C3C916CA-9E74-4083-B724-A20ED3E8EDE7
CrashReporter Key:   0DB29BAC-5A03-5DA0-BE5B-FA4C57FD32EB
Hardware Model:      MacBookPro11,4
Process:         Sketch [44376]
Path:            /Users/USER/Documents/Applications/Sketch.app/Contents/MacOS/Sketch
Identifier:      com.bohemiancoding.sketch3
Version:         48.1 (47250)
Code Type:       X86-64
Parent Process:  launchd [1]

Date/Time:       2018-01-04 08:58:17 +0000
OS Version:      Mac OS X 10.11.6 (15G17023)
Report Version:  104

Exception Type:  SIGABRT
Exception Codes: #0 at 0x7fff8e719f06
Crashed Thread:  31

**Comment by nilshoenson** [comment]
This is known. If you update Sketch to 48.2 it should be fixed. Closing this for now.
