### ISSUE TITLE
"NaN" value in paragraph input field brakes text input behavior

### ISSUE THREAD

**Issue by vedranzidanik** [nilshoenson/shared-text-styles#37]
Version 1.6.1 brakes text input. Seems to be because there is a "NaN" value in the paragraph value input field. New line in text field hides lines underneath, in some cases text field becomes invisible or can't be dragged.
<img width="212" alt="screenshot 2018-02-02 16 55 27" src="https://user-images.githubusercontent.com/6799404/35742168-ef19d140-0839-11e8-8995-190bd8b375c8.png">

**Comment by nilshoenson** [comment]
This doesn't look right, will look into this. For now I'd recommend to create a new export with 1.6.1, and then import it again. This should fix that.

**Comment by vedranzidanik** [comment]
Seems to work fine when exporting and re-importing on 1.6.1. Couldn't check with 1.6.2 since it seems that import is broken. I filed a bug on that. Thanks!
