### ISSUE TITLE
Shared styles don't support opacity

### ISSUE THREAD

**Issue by vedranzidanik** [nilshoenson/shared-text-styles#38]

**Comment by nilshoenson** [comment]
Shared Text Styles does support opacity, but only if you set it in the color picker. Like here: 
<img width="209" alt="screen shot on 2018-02-03 at 12_50_30" src="https://user-images.githubusercontent.com/6165477/35766896-e3f05058-08e0-11e8-843e-45d26dd84bc1.png">

Closing this for now.

**Comment by vedranzidanik** [comment]
Didn't think of trying that... 🤦‍♂️ Thanks!
