### ISSUE TITLE
Import broken in 1.6.2

### ISSUE THREAD

**Issue by vedranzidanik** [nilshoenson/shared-text-styles#40]
When I export styles with 1.6.2 I can't import them in a new file. After selecting a .json file and confirming, nothing happens. I'm using the most recent version of Sketch and plugin.

**Comment by guilhermeioppe** [comment]
I have the same problem. Plugin 1.6.2 and sketch 48.2.

**Comment by nilshoenson** [comment]
Can you guys show me the error you get _after_ running the command by opening Console.app and filtering on Sketch? Everything seems to be working on my end.

![image](https://user-images.githubusercontent.com/6165477/35824249-91e95c0e-0ab2-11e8-9aeb-d2fdae9199b8.png)

**Comment by guilhermeioppe** [comment]
Can't show the error because after selecting any .json file and confirm, nothing happens, no massages, nothing.

**Comment by vedranzidanik** [comment]
I can confirm there is no error message or any other sign that something is wrong. Nothing happens.

**Comment by kharrop** [comment]
✅ loadFramework: `SMFramework` success! «Plugin Output»
NSConcreteNotifyingMutableAttributedString addAttribute:value:range:: nil value
 «Plugin Output»

**Comment by ptribe** [comment]
I'm having the same issue

**Comment by ngemil17** [comment]
Same issue here.

**Comment by jjezowski** [comment]
+1 Having the same issue

**Comment by ennzeh** [comment]
Same issue...
Sketch Version 48.2
Shared Text Styles 1.6.2

**Comment by epun** [comment]
Same issue here also on:
Sketch Version 48.2
Shared Text Styles 1.6.2

**Comment by unconstruct** [comment]
Experiencing the same issue as others describe above.
Sketch Version 48.2
Shared Text Styles 1.6.2

**Comment by nilshoenson** [comment]
I just pushed a new version, which should fix this.

**Comment by kharrop** [comment]
Thanks, @nilshoenson! Works great!

**Comment by vedranzidanik** [comment]
I can also confirm that it now works great! Thanks @nilshoenson!

**Comment by jenmagathan** [comment]
I am having the same issue. 

Sketch 50.2
Plugin 1.6.2

**Comment by biginjapan** [comment]
I am having the same issue.

Sketch 50.2
Plugin 1.6.3

**Comment by myukes** [comment]
+1 on the issue, same behavior. Re-installed both through Sketch plugin manager and Sketch itself, no luck. I had been working in the same project files for a while, so I can't say when exactly it started to happen, but last import before this was probably a few weeks back.

Sketch 50.1
Plugin 1.6.3

Great plugin BTW.

**Comment by DanJackson21** [comment]
Got the latest update (1.7.0) and it works perfect again! Thank you for your help 👍
