### ISSUE TITLE
Does not import text styles to Sketch file

### ISSUE THREAD

**Issue by ogobatzorig** [nilshoenson/shared-text-styles#41]
As of 02.06.18, it stopped importing text styles.

**Comment by nilshoenson** [comment]
Can you be a bit more specific about the version you're using? This doesn't really help.

**Comment by TuiMediaSam** [comment]
I'l add to this - Sketch v.48.2, plugin v. 1.6.3.

A few days ago the plugin wasn't importing text styles at all - that is now working again (thanks!).

The issue I am seeing today, is that whilst the plugin DOES import text styles between documents, if the styles are imported into a new document which contains identically styled text layers, the style is not 'applied' to those layers.

For example:

I make a document with a text layer styled in say, Helvetica, #000, 12pt, I then define it as a style called 'MyTextStyle'. If I copy/paste that text layer into a new document, then import the text styles from the original document, that same text layer will not have a style applied to it in the type menu, even though an identical type style has been imported via the plugin.

I'm not even sure that this is part of the designed functionality, though I'd love it to be. Does that make sense? @nilshoenson

**Comment by nilshoenson** [comment]
I get what you mean, but I don't think this is something I can fix. This feels like a Sketch bug/issue to me. Closing this for now.

**Comment by ogobatzorig** [comment]
Plugin is working now. I think you fixed it @nilshoenson. Thank you.
