### ISSUE TITLE
Latest update would not allow to sync project to Invision

### ISSUE THREAD

**Issue by afiqbinary** [nilshoenson/shared-text-styles#42]
Greetings.

Seems like the latest update (1.6.3) wouldn't allow my team to sync the project to Invision via Craft Manager. From what we can tell from our troubleshoot, my teammates were using the latest update and they faced this issue. But I'm using the 1.5.2, and it works fine. They re-install back the plugin with v1.6.3 and it is working too.

It may sounds like the solution we found is not correlated to the issue, but I don't know how, it works. I hope it helps.

**Comment by nilshoenson** [comment]
This sounds like a bug related to Craft, rather than this plugin. Closing for now.
