### ISSUE TITLE
Not compatible with Sketch 49?

### ISSUE THREAD

**Issue by taiko-hy** [nilshoenson/shared-text-styles#43]
Nothing is happen if I import .json file.

**Comment by onpurpose** [comment]
Have same issue

**Comment by rainbows4dinos** [comment]
Me too. Specifically only seems to import 3 or 4 of the styles and then gives up.

**Comment by drooog** [comment]
Same here. Its broke :-(

**Comment by drooog** [comment]
Ah! The update fixed it... Thanks!

**Comment by nilshoenson** [comment]
I only just updated to Sketch 49, but it looks like everything is working on 49.1. Closing this for now.
