### ISSUE TITLE
version 1.6.2 not working in Sketch 49.1

### ISSUE THREAD

**Issue by aruffo3** [nilshoenson/shared-text-styles#47]
Importing the JSON file has no results.
Sketch 49.1
Plugin 1.6.2
4/3/18 1:06:33.932 PM Sketch[46881]: Exception: NSConcreteNotifyingMutableAttributedString addAttribute:value:range:: nil value

**Comment by johnnycruz** [comment]
I'm experiencing the same issue with Sketch 49.1 and plugin 1.6.2
Confirmed that 'Export Text Styles...' outputs a properly formed JSON.

**Comment by aruffo3** [comment]
Just tried 1.6.3 in version 49.1 of Sketch and things are working fine.

**Comment by jonnycook** [comment]
I've fixed the issue in this fork: https://github.com/jonnycook/shared-text-styles.git (I've created a pull request in this repo)
