### ISSUE TITLE
Version 1.6.2 not working in Sketch 49.2

### ISSUE THREAD

**Issue by blinkstwice** [nilshoenson/shared-text-styles#48]
When I try to export my styles, no window appears to assign a name to the .json file. Unless I am missing something obvious from this process?

**Comment by blinkstwice** [comment]
Here's my error message: "Error: stepSQLStatement:toCompletionWithRetry - stepping returned unhandled result=10, DB=/Users/danielly/Library/Caches/com.bohemiancoding.sketch3/Cache.db"

**Comment by jrharshath** [comment]
I tried with Sketch 49.3 and does not work there either...

**Comment by blinkstwice** [comment]
I just tried 1.6.3, and I got this error message: 
Error: stepSQLStatement:toCompletionWithRetry - stepping returned unhandled result=10, DB=/Users/danielly/Library/Caches/com.bohemiancoding.sketch3/Cache.db
