### ISSUE TITLE
Version 1.6.3 not working in Sketch 49.3

### ISSUE THREAD

**Issue by sartrcrow** [nilshoenson/shared-text-styles#49]
Export text styles option still doesn't working in Sketch 49.3. However import option works great.

**Comment by davidjost** [comment]
I have the same problem, but the other way around. Export works, import doesn't.

**Comment by cpascariello** [comment]
@davidjost +1

**Comment by nickm717** [comment]
Import is not carrying over the fonts properly. Everything changes to 'Apple Color Emoji'.

**Comment by celiamarais** [comment]
Same for me: export works fine, import doesn't
