### ISSUE TITLE
Shared text styles not importing in Sketch 50

### ISSUE THREAD

**Issue by AmirKhan3** [nilshoenson/shared-text-styles#52]
I am trying to import text styles (the same file that I have been using previous to Sketch 50 update). Unfortunately after importing the text styles list is still blank. I am able to apparently export text styles, but it won't let me import anything after making a new file.

**Comment by anniewilson** [comment]
I'm having the same issue!

**Comment by evontay** [comment]
Having the same issue too after updating to Sketch 50. Importing doesn't work for me.

**Comment by cmay-waveapps** [comment]
Same here

**Comment by vitorfernandes** [comment]
same here

**Comment by nilshoenson** [comment]
Thanks for reporting everyone, I'll try and fix it tomorrow.

**Comment by Viditgupta5151** [comment]
@nilshoenson did you happen to fix the issue because I downloaded Sketch 50.2 and still the plugin doesn't work

**Comment by tmolhook** [comment]
just adding to the noise... Having the same issue here on v50.2

**Comment by Anticlimaddox** [comment]
This has been such a huge time saver, hoping for a fix for 50.2.  Thanks. It is much appreciated! Cheers.

**Comment by vedranzidanik** [comment]
The same issue here. Thanks for looking into it!

**Comment by jakriese** [comment]
Ditto, can't import styles in 50.2

**Comment by DanMad** [comment]
I am just chiming in to say the very same: I am running Sketch 50.2 and cannot import text styles. Export looks fine, though.

**Comment by matt-bailey** [comment]
Really hope this can be fixed.

**Comment by bherdrick** [comment]
Any update on the status of fixing this bug would be appreciated as well. I was responsible for my team using this methodology of organizing our text styles and now am looking foolish for doing so.

**Comment by nilshoenson** [comment]
Hey all, sorry it took longer than expected but I just pushed a new version which should fix the importing issue. Thanks for reporting!

**Comment by DanMad** [comment]
Thank you for doing so—much appreciated. I like that you've updated the plugin image too. Very cool...

**Comment by vedranzidanik** [comment]
Thanks @nilshoenson for updating! This is such an essential plugin. 👏

**Comment by Anticlimaddox** [comment]
Much appreciated Nils.
