### ISSUE TITLE
Import Broken 

### ISSUE THREAD

**Issue by ralvarado7** [nilshoenson/shared-text-styles#54]
Nothing happens after I import. 
Sketch 50 
Shared Text Styles 1.6.3

**Comment by vitorfernandes** [comment]
any workaround?

**Comment by vu-j** [comment]
Yeah, broken on Sketch 50 using v. 1.6.3 on my end as well. Looking forward to a fix!

**Comment by nilshoenson** [comment]
Thanks for reporting. Closing this as it's a duplicate of #52.
