### ISSUE TITLE
Plugin does not appear to work in Sketch v40.3 (33839)

### ISSUE THREAD

**Issue by NateBaldwinDesign** [nilshoenson/shared-text-styles#6]
Sketch shared text styles plugin does everything except actually export the text-styles.json file in Sketch 40.3.

**Comment by mridumehta** [comment]
my sketch v40.3 is crashing on importing via shared text styles plugin

**Comment by saffad** [comment]
Doesn't import anymore: I'm on Version 41.2 (35397)
