### ISSUE TITLE
Sketch crashing on import

### ISSUE THREAD

**Issue by tobyhaynes** [nilshoenson/shared-text-styles#65]
Hi

I'm running version 52.3 of Sketch and version 1.8 of Shared text styles but each time I try to import a .json file of the styles Sketch crashes.

It was working before I updated Sketch, any ideas?

**Comment by WendelFelius** [comment]
Same :(

**Comment by nilssonH** [comment]
There was a little typo in the code which made Sketch crash. It should be fixed now!

**Comment by tobyhaynes** [comment]
Perfect, all working now. Thanks!
