### ISSUE TITLE
Paragraph value not stored in json

### ISSUE THREAD

**Issue by russgoodman** [nilshoenson/shared-text-styles#7]
It'd be great to have this info in there, as importing resets all styles to zero which was not the same style I expected to export.

**Comment by allaboutseb** [comment]
@nilshoenson Thanks for creating the plug-in. Unfortunately our text styles rely heavily on the *Paragraph* setting. Could you please include this in any upcoming releases?
Additionally, adding support for the other text option (Decoration, List Type) would be helpful too.

**Comment by antonea** [comment]
Great tool, especially with the introduction of Sketch Libraries and them not exporting the text styles. Would love for the paragraph spacing to pull across as well.

**Comment by supsupmo** [comment]
I was digging into this a bit. It's straightforward to export `paragraphSpacing` into the JSON file. The trouble comes on the import side of things—the Sketch dev library doesn't easy for importing `paragraphSpacing` for a particular text style.

I've submitted a query to Sketch and might look further for a workaround.

**Comment by nilshoenson** [comment]
Sorry this took so long, but thanks to @supsupmo this now works!
