### ISSUE TITLE
Plugin only sporadically exports on Sketch v41.2

### ISSUE THREAD

**Issue by sarahtipton** [nilshoenson/shared-text-styles#8]
I was able to export/import from one Sketch file to another a couple of times without issue, and then it just stopped exporting. There were no error messages thrown. For a test, I put an empty text-styles.json file on my Desktop, exported from Sketch the /new/ text-styles.json, I was asked if I wanted to replace the existing file, to which I said yes and it seemingly "worked". However, when I opened the file, it was still empty.

**Comment by jnouveau** [comment]
Hi there, I'm currently running on Sketch 41.2. When I exported the text styles to a folder, no .json file was found. However, the folder's "date modified" matched the time I exported it at. Help!
